package cli

import (
	"fmt"
	"io"
	"path"
	"strings"
	"time"

	"gitlab.com/codebarge/barge/features/ownership/dto"
	"gitlab.com/codebarge/barge/features/ownership/service"
)

// TeamURL is where the handover checklist points people who want the
// questions asked and the answers kept automatically.
const TeamURL = "https://gitlab.com/codebarge/barge#team-version"

// RenderHandover writes a Markdown handover checklist. It is meant to be
// saved, shared with the team and ticked off, so it uses plain Markdown
// that renders in GitLab, GitHub and most editors.
func RenderHandover(w io.Writer, h dto.Handover, meta Header) {
	name := h.Person.Name
	first := firstName(name)
	orphaned := 0
	for _, m := range h.Modules {
		if m.BusFactorAfter == 0 {
			orphaned++
		}
	}

	fmt.Fprintf(w, "# Handover: %s\n\n", name)
	fmt.Fprintf(w, "_Repository **%s** (%s), history up to %s. Generated by Barge on %s._\n\n",
		meta.Repo, meta.Rev, h.AsOf.Format(time.DateOnly), time.Now().Format(time.DateOnly))

	if len(h.Modules) == 0 {
		fmt.Fprintf(w, "%s is not a key owner of any module: nobody depends on their knowledge alone. No handover needed.\n", name)
		return
	}

	fmt.Fprintf(w, "%s is a key owner of %d module%s.", name, len(h.Modules), plural(len(h.Modules)))
	if orphaned > 0 {
		fmt.Fprintf(w, " Without a handover, **%d of them would have nobody who knows them**.", orphaned)
	}
	fmt.Fprint(w, " Go through the questions together, write the answers down next to the code, and pair the suggested successor on the next changes.\n\n")

	fmt.Fprintf(w, "| Module | %s's share | Bus factor after | Risk after | Suggested successor |\n", first)
	fmt.Fprintln(w, "| --- | ---: | ---: | --- | --- |")
	for _, m := range h.Modules {
		succ := m.CandidateName
		if succ == "" {
			succ = "—"
		}
		fmt.Fprintf(w, "| `%s` | %d%% | %d | %s | %s |\n", shortPath(m.Path), pct(m.Share), m.BusFactorAfter, m.RiskAfter, succ)
	}

	for _, m := range h.Modules {
		fmt.Fprintf(w, "\n## `%s`\n\n", shortPath(m.Path))
		fmt.Fprintf(w, "%s's share: **%d%%** · last change: %s · after the departure: bus factor **%d** (%s)\n",
			first, pct(m.Share), m.LastTouch.Format(time.DateOnly), m.BusFactorAfter, m.RiskAfter)
		if m.CandidateName != "" {
			fmt.Fprintf(w, "\nSuggested successor: **%s** (already worked on this code or next to it).\n", m.CandidateName)
		} else {
			fmt.Fprint(w, "\nNo obvious successor: nobody active has worked on this code. Pick one before the handover.\n")
		}

		if len(m.OwnFiles) > 0 {
			fmt.Fprintf(w, "\nFiles mostly written by %s:\n\n", first)
			for _, f := range m.OwnFiles {
				fmt.Fprintf(w, "- `%s` (%d%% of all changes)\n", f.Path, pct(f.Share))
			}
		}

		fmt.Fprintf(w, "\n### Questions for %s\n\n", first)
		for _, q := range service.Questions(m) {
			switch {
			case q.Commit != nil:
				c := q.Commit
				fmt.Fprintf(w, "- [ ] `%s` “%s” (%s", short(c.Hash), clean(c.Subject), c.Time.Format(time.DateOnly))
				if q.Kind == dto.QuestionCommit {
					fmt.Fprintf(w, ", %d lines", c.Lines)
				}
				fmt.Fprintf(w, "): %s\n", lowerFirst(q.Prompt))
			case len(q.Files) > 0:
				names := make([]string, 0, len(q.Files))
				for _, f := range q.Files {
					names = append(names, "`"+path.Base(f)+"`")
				}
				fmt.Fprintf(w, "- [ ] Which of %s is the most fragile, and how do you test changes to it?\n", strings.Join(names, ", "))
			default:
				fmt.Fprintf(w, "- [ ] %s\n", q.Prompt)
			}
		}
		if m.CandidateName != "" {
			fmt.Fprintf(w, "\n### For %s\n\n", m.CandidateName)
			fmt.Fprintf(w, "- [ ] Pair with %s on the next change in this module\n", first)
			fmt.Fprintf(w, "- [ ] Review every change to it until %s leaves\n", first)
			fmt.Fprintln(w, "- [ ] Write the answers above into the module's README")
		}
	}

	fmt.Fprintf(w, "\n---\n\n_Barge for teams asks these questions automatically, keeps the answers next to the code and gives them to your AI coding agents: %s_\n", TeamURL)
}

func firstName(name string) string {
	f := strings.Fields(name)
	if len(f) == 0 {
		return name
	}
	return f[0]
}

func short(hash string) string {
	if len(hash) > 7 {
		return hash[:7]
	}
	return hash
}

// clean keeps a commit subject from breaking the Markdown around it.
func clean(s string) string {
	s = strings.ReplaceAll(s, "`", "'")
	return clip(strings.TrimSpace(s), 100)
}

// lowerFirst: "Why was it…" -> "why was it…", to follow a colon.
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
