package service

import (
	"math"
	"sort"
	"strings"
	"time"

	"gitlab.com/codebarge/barge/features/ownership/dto"
)

// Analyzer accumulates commits and produces a Report. It is fed commits one
// at a time, newest first, so memory stays proportional to modules × people,
// not to the size of the history.
type Analyzer struct {
	cfg       Config
	files     map[string]int64 // paths present at the analysed revision -> size
	generated map[string]bool
	exclude   matcher
	modules   *moduler

	renames map[string]string // old path -> path at the analysed revision
	touched map[string]bool   // files with at least one text change in history
	ids     *identities

	t0      time.Time // decay reference; weights are stored relative to it
	t0Set   bool
	newest  time.Time
	commits int

	mods   map[string]*acc // module path -> accumulator
	groups map[string]*acc // directory path -> accumulator (aggregated)
}

type acc struct {
	weight    map[string]float64 // identity key -> decayed weight
	lastTouch map[string]time.Time
	commits   int
	lastHash  string
	lines     float64 // decayed changed lines
	aiLines   float64 // decayed changed lines from AI-assisted commits
}

func newAcc() *acc {
	return &acc{weight: make(map[string]float64), lastTouch: make(map[string]time.Time)}
}

// NewAnalyzer prepares an analysis of the given files. generated lists
// paths detected as generated by their content; it may be nil.
func NewAnalyzer(cfg Config, files []dto.File, generated map[string]bool) *Analyzer {
	patterns := cfg.Exclude
	if !cfg.NoDefaultExcludes {
		patterns = append(append([]string{}, DefaultExclude...), cfg.Exclude...)
	}
	a := &Analyzer{
		cfg:       cfg,
		files:     make(map[string]int64, len(files)),
		generated: generated,
		exclude:   newMatcher(patterns),
		modules:   newModuler(cfg.ModuleRules, cfg.Depth),
		renames:   make(map[string]string),
		touched:   make(map[string]bool),
		ids:       newIdentities(),
		mods:      make(map[string]*acc),
		groups:    make(map[string]*acc),
	}
	for _, f := range files {
		a.files[f.Path] = f.Size
	}
	if !cfg.AsOf.IsZero() {
		a.t0, a.t0Set = cfg.AsOf, true
	}
	return a
}

// counts reports whether a file at the analysed revision carries knowledge.
func (a *Analyzer) counts(p string) bool {
	if _, ok := a.files[p]; !ok {
		return false // deleted since: nobody needs to know it any more
	}
	if a.generated[p] {
		return false
	}
	return !a.exclude.match(p)
}

// resolve follows renames forward to the path at the analysed revision.
func (a *Analyzer) resolve(p string) string {
	for i := 0; i < 64; i++ {
		next, ok := a.renames[p]
		if !ok || next == p {
			return p
		}
		p = next
	}
	return p
}

// item is one counted file change, with its path at the analysed revision.
type item struct {
	path  string
	lines int
}

// items follows renames and keeps the changes that carry knowledge.
// Renames are tracked for every commit, even ones we do not credit.
func (a *Analyzer) items(c dto.Commit) []item {
	items := make([]item, 0, len(c.Changes))
	for _, ch := range c.Changes {
		cur := a.resolve(ch.Path)
		if ch.OldPath != "" && ch.OldPath != cur {
			a.renames[ch.OldPath] = cur
		}
		if ch.Binary || !a.counts(cur) {
			continue
		}
		a.touched[cur] = true
		items = append(items, item{cur, ch.Added + ch.Removed})
	}
	return items
}

// Add feeds one commit. Commits must arrive newest first.
func (a *Analyzer) Add(c dto.Commit) {
	if c.Time.After(a.newest) {
		a.newest = c.Time
	}
	if !a.t0Set {
		a.t0, a.t0Set = c.Time, true
	}

	items := a.items(c)
	if len(items) == 0 {
		return
	}

	kind := classifyAuthor(c.Author, c.Email)
	if kind == kindBot {
		return
	}
	ai := kind == kindAgent || isAIAssisted(c)

	var key string
	if kind == kindHuman {
		key = a.ids.observe(c.Author, c.Email, c.Time)
	}
	a.commits++

	scale := 1.0
	if a.cfg.MassChangeFiles > 0 && len(items) > a.cfg.MassChangeFiles {
		scale = a.cfg.MassChangeWeight
	}
	human := scale
	if ai {
		human *= a.cfg.AIWeight
	}
	decay := a.decay(c.Time)

	for _, it := range items {
		mod := a.modules.moduleOf(it.path)
		lines := float64(it.lines) * decay
		w := math.Log1p(float64(it.lines)) * decay * human
		if it.lines == 0 {
			// A pure rename still shows the person touched the file.
			w = 0.1 * decay * human
		}
		a.credit(a.mod(mod), c, key, kind, w, lines, ai)
		a.credit(a.group(mod), c, key, kind, w, lines, ai)
		for _, anc := range ancestors(mod) {
			a.credit(a.group(anc), c, key, kind, w, lines, ai)
		}
	}
}

func (a *Analyzer) credit(m *acc, c dto.Commit, key string, kind authorKind, w, lines float64, ai bool) {
	if m.lastHash != c.Hash {
		m.lastHash = c.Hash
		m.commits++
	}
	m.lines += lines
	if ai {
		m.aiLines += lines
	}
	if kind != kindHuman || w <= 0 {
		return
	}
	m.weight[key] += w
	if c.Time.After(m.lastTouch[key]) {
		m.lastTouch[key] = c.Time
	}
}

func (a *Analyzer) mod(p string) *acc {
	m, ok := a.mods[p]
	if !ok {
		m = newAcc()
		a.mods[p] = m
	}
	return m
}

func (a *Analyzer) group(p string) *acc {
	m, ok := a.groups[p]
	if !ok {
		m = newAcc()
		a.groups[p] = m
	}
	return m
}

// decay returns 2^((t - t0) / halfLife). Weights are kept relative to t0;
// shares are ratios, so the common factor cancels out.
func (a *Analyzer) decay(t time.Time) float64 {
	if a.cfg.HalfLife <= 0 {
		return 1
	}
	return math.Exp2(float64(t.Sub(a.t0)) / float64(a.cfg.HalfLife))
}

// Report computes owners, bus factor and risk for every module.
func (a *Analyzer) Report() dto.Report {
	asOf := a.cfg.AsOf
	if asOf.IsZero() {
		asOf = a.newest
	}
	people, keyToID := a.ids.people()
	a.applyStatuses(people, asOf)
	byID := make(map[string]*dto.Person, len(people))
	for i := range people {
		byID[people[i].ID] = &people[i]
	}
	overrides := a.overrides(people)

	// Sizes come from the file list, so modules without any credited
	// history still show up (as orphaned).
	type size struct {
		files int
		bytes int64
	}
	modSize := make(map[string]*size)
	groupSize := make(map[string]*size)
	hasChildModule := make(map[string]bool)
	addSize := func(m map[string]*size, k string, b int64) {
		s := m[k]
		if s == nil {
			s = &size{}
			m[k] = s
		}
		s.files++
		s.bytes += b
	}
	for p, b := range a.files {
		// Files that never had a text change (images, fonts) or whose
		// history is invisible to us carry no knowledge we can measure.
		if !a.touched[p] || !a.counts(p) {
			continue
		}
		mod := a.modules.moduleOf(p)
		addSize(modSize, mod, b)
		addSize(groupSize, mod, b)
		for _, anc := range ancestors(mod) {
			addSize(groupSize, anc, b)
		}
	}
	for mod := range modSize {
		for _, anc := range ancestors(mod) {
			hasChildModule[anc] = true
		}
	}

	build := func(p, kind string, m *acc, s *size) dto.Module {
		if m == nil {
			m = newAcc()
		}
		out := dto.Module{Path: p, Parent: parentOf(p), Kind: kind, Commits: m.commits}
		if s != nil {
			out.Files, out.Bytes = s.files, s.bytes
		}
		var ov map[string]bool
		if kind == dto.KindModule {
			ov = overrides[p]
		}
		a.fillOwners(&out, m, keyToID, byID, ov)
		a.classify(&out, byID)
		return out
	}

	rep := dto.Report{AsOf: asOf, Commits: a.commits, People: people}
	for p, s := range modSize {
		mod := build(p, dto.KindModule, a.mods[p], s)
		rep.Modules = append(rep.Modules, mod)
		countSummary(&rep.Summary, mod)
	}
	sort.Slice(rep.Modules, func(i, j int) bool {
		x, y := rep.Modules[i], rep.Modules[j]
		if x.Risk.Rank() != y.Risk.Rank() {
			return x.Risk.Rank() < y.Risk.Rank()
		}
		if x.Bytes != y.Bytes {
			return x.Bytes > y.Bytes
		}
		return x.Path < y.Path
	})

	var groups []dto.Module
	for p, s := range groupSize {
		// A leaf module's own group would repeat the module: skip it.
		// The root group stays: it carries the repository-wide numbers.
		if _, isModule := modSize[p]; isModule && !hasChildModule[p] && p != "." {
			continue
		}
		groups = append(groups, build(p, dto.KindGroup, a.groups[p], s))
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i].Path < groups[j].Path })
	rep.Modules = append(rep.Modules, groups...)
	rep.Actions = recommend(rep, a.cfg.OwnerShare)
	return rep
}

// applyStatuses sets each person's status: explicit statuses win,
// otherwise people without recent commits are inactive.
func (a *Analyzer) applyStatuses(people []dto.Person, asOf time.Time) {
	explicit := make(map[string]dto.PersonStatus)
	for _, s := range a.cfg.Statuses {
		explicit[normalizeEmail(s.Email)] = s
	}
	for i := range people {
		p := &people[i]
		p.Status = dto.StatusActive
		if a.cfg.ActiveWindow > 0 && asOf.Sub(p.LastCommit) > a.cfg.ActiveWindow {
			p.Status = dto.StatusInactive
		}
		for _, e := range p.Emails {
			if s, ok := explicit[e]; ok {
				p.Status = s.Status
				p.LeaveDate = s.Date
				break
			}
		}
	}
}

// overrides resolves Config.Owners to person IDs: module path -> person ID
// -> knows. Overrides for e-mails nobody committed with are ignored.
func (a *Analyzer) overrides(people []dto.Person) map[string]map[string]bool {
	if len(a.cfg.Owners) == 0 {
		return nil
	}
	byEmail := make(map[string]string)
	for _, p := range people {
		for _, e := range p.Emails {
			byEmail[e] = p.ID
		}
	}
	out := make(map[string]map[string]bool)
	for _, o := range a.cfg.Owners {
		id, ok := byEmail[normalizeEmail(o.Email)]
		if !ok {
			continue
		}
		mod := CleanModulePath(o.Module)
		if out[mod] == nil {
			out[mod] = make(map[string]bool)
		}
		out[mod][id] = o.Knows
	}
	return out
}

// CleanModulePath normalises a module path written by a person:
// "./internal/core/" -> "internal/core", "" -> ".".
func CleanModulePath(p string) string {
	p = strings.Trim(strings.TrimSpace(strings.ReplaceAll(p, "\\", "/")), "/")
	for strings.HasPrefix(p, "./") {
		p = strings.TrimLeft(strings.TrimPrefix(p, "./"), "/")
	}
	if p == "" {
		return "."
	}
	return p
}

// fillOwners computes shares from the decayed weights, then applies the
// module's overrides (person ID -> knows).
func (a *Analyzer) fillOwners(m *dto.Module, acc *acc, keyToID map[string]string, byID map[string]*dto.Person, ov map[string]bool) {
	if acc.lines > 0 {
		m.AIShare = acc.aiLines / acc.lines
	}
	weights := make(map[string]float64)
	touch := make(map[string]time.Time)
	var total float64
	for k, w := range acc.weight {
		id := keyToID[k]
		if knows, ok := ov[id]; ok && !knows {
			continue
		}
		weights[id] += w
		total += w
		if acc.lastTouch[k].After(touch[id]) {
			touch[id] = acc.lastTouch[k]
		}
	}
	for id, w := range weights {
		share := w / total
		if share < 0.01 && !ov[id] {
			continue // noise: a typo fix three years ago
		}
		p := byID[id]
		m.Owners = append(m.Owners, dto.Owner{
			PersonID: id, Name: p.Name, Share: share, LastTouch: touch[id], Status: p.Status, Confirmed: ov[id],
		})
	}
	for id, knows := range ov {
		if _, listed := weights[id]; knows && !listed {
			p := byID[id]
			m.Owners = append(m.Owners, dto.Owner{PersonID: id, Name: p.Name, Status: p.Status, Confirmed: true})
		}
	}
	sort.Slice(m.Owners, func(i, j int) bool {
		if m.Owners[i].Share != m.Owners[j].Share {
			return m.Owners[i].Share > m.Owners[j].Share
		}
		return m.Owners[i].PersonID < m.Owners[j].PersonID
	})
}

// classify computes the bus factor and the risk level with its reasons.
func (a *Analyzer) classify(m *dto.Module, byID map[string]*dto.Person) {
	var present []float64
	var presentSum, leavingSum float64
	th := a.cfg.KnowledgeThreshold
	for _, o := range m.Owners {
		switch byID[o.PersonID].Status {
		case dto.StatusActive:
			share := o.Share
			if o.Confirmed && share < th {
				share = th // confirmed: enough to keep the module going alone
			}
			present = append(present, share)
			presentSum += share
		case dto.StatusLeaving:
			leavingSum += o.Share
		}
	}
	m.BusFactor = BusFactor(present, th)

	add := func(r dto.Reason) {
		for _, x := range m.Reasons {
			if x == r {
				return
			}
		}
		m.Reasons = append(m.Reasons, r)
	}
	switch {
	case m.BusFactor == 0 && leavingSum > 0 && presentSum+leavingSum >= th-eps:
		m.Risk = dto.RiskCritical
		add(dto.ReasonOwnerLeaving)
	case m.BusFactor == 0:
		m.Risk = dto.RiskCritical
		add(dto.ReasonOrphaned)
	case m.BusFactor == 1:
		m.Risk = dto.RiskHigh
		add(dto.ReasonSingleOwner)
	case m.BusFactor == 2:
		m.Risk = dto.RiskMedium
		add(dto.ReasonTwoOwners)
	default:
		m.Risk = dto.RiskLow
	}
	if leavingSum >= a.cfg.OwnerShare {
		add(dto.ReasonOwnerLeaving)
	}
	if a.cfg.AIShareThreshold > 0 && m.AIShare >= a.cfg.AIShareThreshold {
		add(dto.ReasonAIHeavy)
		if m.Risk == dto.RiskLow {
			m.Risk = dto.RiskMedium
		}
	}
	if m.Commits < a.cfg.MinCommits {
		add(dto.ReasonLowHistory)
	}
}

const eps = 1e-9

// BusFactor returns how many of the present people, removed in order of
// decreasing share, must leave before the rest hold less than threshold of
// the knowledge. Shares need not sum to 1: people who already left simply
// are not in the list.
//
//	[1.0] -> 1, [0.5 0.5] -> 2, [0.86 0.09 0.05] -> 1, [] -> 0
func BusFactor(shares []float64, threshold float64) int {
	s := append([]float64(nil), shares...)
	sort.Sort(sort.Reverse(sort.Float64Slice(s)))
	var remaining float64
	for _, x := range s {
		remaining += x
	}
	n := 0
	for n < len(s) && remaining >= threshold-eps {
		remaining -= s[n]
		n++
	}
	return n
}

func countSummary(s *dto.Summary, m dto.Module) {
	s.Modules++
	switch m.Risk {
	case dto.RiskCritical:
		s.Critical++
	case dto.RiskHigh:
		s.High++
	case dto.RiskMedium:
		s.Medium++
	default:
		s.Low++
	}
	switch m.BusFactor {
	case 0:
		s.Orphaned++
	case 1:
		s.SingleOwner++
	}
}
