// Package gitsource implements service.Source on top of a git repository.
// The CLI uses it on a local checkout, the server on its bare clones.
package gitsource

import (
	"context"

	"gitlab.com/codebarge/barge/core/git"
	"gitlab.com/codebarge/barge/features/ownership/dto"
)

// Source reads history at one revision of a repository.
type Source struct {
	Repo *git.Repo
	Rev  string // "" means HEAD
}

// New returns a Source for repo at rev.
func New(repo *git.Repo, rev string) *Source {
	if rev == "" {
		rev = "HEAD"
	}
	return &Source{Repo: repo, Rev: rev}
}

// Files lists the files present at the revision.
func (s *Source) Files(ctx context.Context) ([]dto.File, error) {
	fs, err := s.Repo.Files(ctx, s.Rev)
	if err != nil {
		return nil, err
	}
	out := make([]dto.File, len(fs))
	for i, f := range fs {
		out[i] = dto.File{Path: f.Path, Size: f.Size}
	}
	return out, nil
}

// Generated lists files marked as generated by their content.
func (s *Source) Generated(ctx context.Context) (map[string]bool, error) {
	return s.Repo.Generated(ctx, s.Rev)
}

// Commits streams the history newest first.
func (s *Source) Commits(ctx context.Context, fn func(dto.Commit) error) error {
	return s.Repo.Log(ctx, git.LogOptions{Rev: s.Rev}, func(c git.Commit) error {
		out := dto.Commit{
			Hash: c.Hash, Author: c.Author, Email: c.Email, Time: c.Time, Message: c.Message,
			Changes: make([]dto.Change, len(c.Changes)),
		}
		for i, ch := range c.Changes {
			out.Changes[i] = dto.Change{
				Path: ch.Path, OldPath: ch.OldPath, Added: ch.Added, Removed: ch.Removed, Binary: ch.Binary,
			}
		}
		return fn(out)
	})
}
