package git

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestParseLog(t *testing.T) {
	raw := "\x1eaaa\x1fAnn A\x1fann@x.io\x1f1700000000\x1fmove files\n\nCo-authored-by: Claude <noreply@anthropic.com>\n\x1f\n\n" +
		"3\t1\tsrc/{old => new}/a.go\n" +
		"-\t-\tlogo.png\n" +
		"10\t0\t\"weird\\tname.go\"\n" +
		"\x1ebbb\x1fBob\x1fbob@x.io\x1f1690000000\x1ffirst\n\x1f\n\n" +
		"5\t0\tREADME.md\n"

	var got []Commit
	err := ParseLog(strings.NewReader(raw), func(c Commit) error {
		got = append(got, c)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 2 {
		t.Fatalf("want 2 commits, got %d", len(got))
	}
	c := got[0]
	if c.Hash != "aaa" || c.Author != "Ann A" || c.Email != "ann@x.io" {
		t.Errorf("bad header: %+v", c)
	}
	if !c.Time.Equal(time.Unix(1700000000, 0)) {
		t.Errorf("bad time %v", c.Time)
	}
	if !strings.Contains(c.Message, "Co-authored-by: Claude") {
		t.Errorf("message lost trailers: %q", c.Message)
	}
	if len(c.Changes) != 3 {
		t.Fatalf("want 3 changes, got %+v", c.Changes)
	}
	if ch := c.Changes[0]; ch.Path != "src/new/a.go" || ch.OldPath != "src/old/a.go" || ch.Added != 3 || ch.Removed != 1 {
		t.Errorf("rename parsed wrong: %+v", ch)
	}
	if !c.Changes[1].Binary {
		t.Errorf("binary not detected: %+v", c.Changes[1])
	}
	if c.Changes[2].Path != "weird\tname.go" {
		t.Errorf("quoted path: %q", c.Changes[2].Path)
	}
	if got[1].Hash != "bbb" || len(got[1].Changes) != 1 {
		t.Errorf("second commit: %+v", got[1])
	}
}

func TestSplitRename(t *testing.T) {
	cases := []struct{ in, old, new string }{
		{"src/{a.go => b.go}", "src/a.go", "src/b.go"},
		{"{src => pkg}/b.go", "src/b.go", "pkg/b.go"},
		{"src/{ => sub}/a.go", "src/a.go", "src/sub/a.go"},
		{"src/{sub => }/a.go", "src/sub/a.go", "src/a.go"},
		{"a.go => b.go", "a.go", "b.go"},
	}
	for _, tc := range cases {
		o, n, ok := SplitRename(tc.in)
		if !ok || o != tc.old || n != tc.new {
			t.Errorf("SplitRename(%q) = %q, %q, %v; want %q, %q", tc.in, o, n, ok, tc.old, tc.new)
		}
	}
	if _, _, ok := SplitRename("plain/path.go"); ok {
		t.Error("plain path reported as rename")
	}
}

// TestRepoIntegration runs real git against a temporary repository.
func TestRepoIntegration(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not installed")
	}
	dir := t.TempDir()
	run := func(env []string, args ...string) {
		t.Helper()
		cmd := exec.Command("git", args...)
		cmd.Dir = dir
		cmd.Env = append(os.Environ(), env...)
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}
	write := func(name, content string) {
		t.Helper()
		p := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	as := func(name, email, date string) []string {
		return []string{
			"GIT_AUTHOR_NAME=" + name, "GIT_AUTHOR_EMAIL=" + email, "GIT_AUTHOR_DATE=" + date,
			"GIT_COMMITTER_NAME=" + name, "GIT_COMMITTER_EMAIL=" + email, "GIT_COMMITTER_DATE=" + date,
		}
	}

	run(nil, "init", "-q", "-b", "main")
	write("svc/a.go", "package svc\n\nfunc A() {}\n")
	write("gen/x.pb.go", "// Code generated by protoc. DO NOT EDIT.\npackage gen\n")
	run(nil, "add", ".")
	run(as("Ann", "ann@x.io", "2024-01-01T10:00:00Z"), "commit", "-q", "-m", "init")
	run(nil, "mv", "svc/a.go", "svc/b.go")
	run(as("Bob", "bob@x.io", "2024-02-01T10:00:00Z"), "commit", "-q", "-m", "rename")

	ctx := context.Background()
	repo, err := Open(ctx, filepath.Join(dir, "svc"))
	if err != nil {
		t.Fatal(err)
	}
	var commits []Commit
	if err := repo.Log(ctx, LogOptions{}, func(c Commit) error { commits = append(commits, c); return nil }); err != nil {
		t.Fatal(err)
	}
	if len(commits) != 2 || commits[0].Author != "Bob" || commits[1].Author != "Ann" {
		t.Fatalf("unexpected commits: %+v", commits)
	}
	if ch := commits[0].Changes; len(ch) != 1 || ch[0].OldPath != "svc/a.go" || ch[0].Path != "svc/b.go" {
		t.Errorf("rename not detected: %+v", ch)
	}

	files, err := repo.Files(ctx, "HEAD")
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 2 {
		t.Errorf("want 2 files, got %+v", files)
	}

	gen, err := repo.Generated(ctx, "HEAD")
	if err != nil {
		t.Fatal(err)
	}
	if !gen["gen/x.pb.go"] || gen["svc/b.go"] {
		t.Errorf("generated detection wrong: %v", gen)
	}

	branch, err := repo.DefaultBranch(ctx)
	if err != nil || branch != "main" {
		t.Errorf("default branch %q, %v", branch, err)
	}

	// A bare clone through the restricted transport must refuse file://.
	if _, err := CloneBare(ctx, "file://"+dir, filepath.Join(t.TempDir(), "x.git"), nil); err == nil {
		t.Error("file:// clone should be blocked")
	}
}
