package git

import (
	"bufio"
	"bytes"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strconv"
	"strings"
)

// ErrNotRepository is returned when Dir is not inside a git repository.
var ErrNotRepository = errors.New("not a git repository")

// Repo runs git commands against one repository (a work tree or a bare clone).
type Repo struct {
	Dir string
}

// Open checks that dir is a git repository and returns its top-level path
// (or the git dir for bare repositories).
func Open(ctx context.Context, dir string) (*Repo, error) {
	r := &Repo{Dir: dir}
	out, err := r.output(ctx, nil, "rev-parse", "--is-bare-repository")
	if err != nil {
		return nil, fmt.Errorf("%w: %s", ErrNotRepository, dir)
	}
	if strings.TrimSpace(string(out)) == "false" {
		top, err := r.output(ctx, nil, "rev-parse", "--show-toplevel")
		if err == nil && strings.TrimSpace(string(top)) != "" {
			r.Dir = strings.TrimSpace(string(top))
		}
	}
	return r, nil
}

// File is one blob at a revision.
type File struct {
	Path string
	Size int64 // bytes
}

// LogOptions selects the commits to read.
type LogOptions struct {
	// Rev is a revision or range: "HEAD", "main", "abc123..main".
	// Empty means HEAD.
	Rev string
}

// Log streams commits newest first. Merge commits are skipped: their
// changes are already counted in the commits they merge.
func (r *Repo) Log(ctx context.Context, opts LogOptions, fn func(Commit) error) error {
	rev := opts.Rev
	if rev == "" {
		rev = "HEAD"
	}
	args := []string{
		"-c", "core.quotepath=off",
		"-c", "log.showSignature=false",
		"log", "--no-merges", "--no-color", "--no-ext-diff", "--no-textconv",
		"-M", "--numstat", "--format=" + logFormat,
		rev, "--",
	}
	return r.stream(ctx, args, func(out io.Reader) error { return ParseLog(out, fn) })
}

// Files lists blobs at rev with their sizes. Submodules are skipped.
func (r *Repo) Files(ctx context.Context, rev string) ([]File, error) {
	if rev == "" {
		rev = "HEAD"
	}
	var files []File
	err := r.stream(ctx, []string{"ls-tree", "-r", "-l", "-z", "--full-tree", rev}, func(out io.Reader) error {
		sc := bufio.NewScanner(out)
		sc.Buffer(make([]byte, 64<<10), 4<<20)
		sc.Split(splitNUL)
		for sc.Scan() {
			// "<mode> <type> <object> <size>\t<path>"
			meta, p, ok := strings.Cut(sc.Text(), "\t")
			if !ok {
				continue
			}
			f := strings.Fields(meta)
			if len(f) != 4 || f[1] != "blob" {
				continue
			}
			size, _ := strconv.ParseInt(f[3], 10, 64)
			files = append(files, File{Path: p, Size: size})
		}
		return sc.Err()
	})
	return files, err
}

// generatedMarkers are the usual "this file is generated" headers across
// ecosystems. Matching files are excluded from ownership.
var generatedMarkers = []string{
	`Code generated .* DO NOT EDIT`, // Go
	`@generated`,                    // many tools, lock files
	`<auto-generated`,               // .NET
}

// Generated returns paths at rev whose content carries a generated-code marker.
func (r *Repo) Generated(ctx context.Context, rev string) (map[string]bool, error) {
	if rev == "" {
		rev = "HEAD"
	}
	args := []string{"-c", "core.quotepath=off", "grep", "-l", "-I", "-z", "--no-color", "-E"}
	for _, m := range generatedMarkers {
		args = append(args, "-e", m)
	}
	args = append(args, rev, "--")
	out, err := r.output(ctx, nil, args...)
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) && exitErr.ExitCode() == 1 {
			return map[string]bool{}, nil // no matches
		}
		return nil, err
	}
	res := make(map[string]bool)
	prefix := rev + ":"
	for _, p := range bytes.Split(out, []byte{0}) {
		if s := strings.TrimPrefix(string(p), prefix); s != "" {
			res[s] = true
		}
	}
	return res, nil
}

// ErrNoSuchFile is returned by ReadFile when the path does not exist at rev.
var ErrNoSuchFile = errors.New("no such file at revision")

// ReadFile returns the content of path at rev.
func (r *Repo) ReadFile(ctx context.Context, rev, path string) ([]byte, error) {
	if rev == "" {
		rev = "HEAD"
	}
	out, err := r.output(ctx, nil, "cat-file", "blob", rev+":"+path)
	if err != nil {
		var ce *CommandError
		if errors.As(err, &ce) && (strings.Contains(ce.Stderr, "does not exist") || strings.Contains(ce.Stderr, "Not a valid object") || strings.Contains(ce.Stderr, "bad file")) {
			return nil, ErrNoSuchFile
		}
		return nil, err
	}
	return out, nil
}

// ResolveRev returns the full hash of rev.
func (r *Repo) ResolveRev(ctx context.Context, rev string) (string, error) {
	out, err := r.output(ctx, nil, "rev-parse", "--verify", "--quiet", rev+"^{commit}")
	if err != nil {
		return "", fmt.Errorf("resolve %s: %w", rev, err)
	}
	return strings.TrimSpace(string(out)), nil
}

// DefaultBranch returns the branch HEAD points to ("main", "master", ...).
func (r *Repo) DefaultBranch(ctx context.Context) (string, error) {
	out, err := r.output(ctx, nil, "symbolic-ref", "--short", "HEAD")
	if err != nil {
		return "", fmt.Errorf("detect default branch: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}

// IsAncestor reports whether a is an ancestor of b.
func (r *Repo) IsAncestor(ctx context.Context, a, b string) bool {
	_, err := r.output(ctx, nil, "merge-base", "--is-ancestor", a, b)
	return err == nil
}

// Auth is HTTP basic credentials for cloning private repositories.
// GitHub tokens use username "x-access-token", GitLab tokens "oauth2".
type Auth struct {
	Username string
	Token    string
}

// env passes the token through environment variables (git >= 2.31), so it
// never appears in process arguments, URLs or the repository config.
func (a *Auth) env() []string {
	if a == nil || a.Token == "" {
		return nil
	}
	cred := base64.StdEncoding.EncodeToString([]byte(a.Username + ":" + a.Token))
	return []string{
		"GIT_CONFIG_COUNT=1",
		"GIT_CONFIG_KEY_0=http.extraHeader",
		"GIT_CONFIG_VALUE_0=Authorization: Basic " + cred,
	}
}

// remoteEnv restricts network operations to http(s): no file://, ssh or
// ext:: transports, no interactive prompts.
var remoteEnv = []string{
	"GIT_ALLOW_PROTOCOL=https:http",
	"GIT_TERMINAL_PROMPT=0",
}

// CloneBare makes a bare clone of url into dir.
func CloneBare(ctx context.Context, url, dir string, auth *Auth) (*Repo, error) {
	env := append(append([]string{}, remoteEnv...), auth.env()...)
	r := &Repo{Dir: "."}
	if _, err := r.output(ctx, env, "clone", "--bare", "--quiet", "--no-tags", "--", url, dir); err != nil {
		return nil, fmt.Errorf("git clone: %w", err)
	}
	return &Repo{Dir: dir}, nil
}

// Fetch updates all branches of a bare clone from origin.
func (r *Repo) Fetch(ctx context.Context, auth *Auth) error {
	env := append(append([]string{}, remoteEnv...), auth.env()...)
	_, err := r.output(ctx, env, "fetch", "--quiet", "--prune", "--no-tags", "origin", "+refs/heads/*:refs/heads/*")
	if err != nil {
		return fmt.Errorf("git fetch: %w", err)
	}
	return nil
}

// Version returns the installed git version, e.g. "2.43.0".
func Version(ctx context.Context) (string, error) {
	r := &Repo{Dir: "."}
	out, err := r.output(ctx, nil, "version")
	if err != nil {
		return "", err
	}
	s := strings.TrimSpace(string(out))
	s = strings.TrimPrefix(s, "git version ")
	if i := strings.IndexByte(s, ' '); i > 0 {
		s = s[:i]
	}
	return s, nil
}

// --- exec helpers ---

func (r *Repo) command(ctx context.Context, env []string, args ...string) *exec.Cmd {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = r.Dir
	cmd.Env = append(os.Environ(), "LC_ALL=C", "GIT_PAGER=cat", "GIT_TERMINAL_PROMPT=0")
	cmd.Env = append(cmd.Env, env...)
	return cmd
}

func (r *Repo) output(ctx context.Context, env []string, args ...string) ([]byte, error) {
	cmd := r.command(ctx, env, args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return out, &CommandError{Args: args, Stderr: strings.TrimSpace(stderr.String()), Err: err}
	}
	return out, nil
}

// stream runs git and hands stdout to read. If read fails, git is killed.
func (r *Repo) stream(ctx context.Context, args []string, read func(io.Reader) error) error {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	cmd := r.command(ctx, nil, args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("start git: %w", err)
	}
	readErr := read(out)
	if readErr != nil {
		cancel()
		_, _ = io.Copy(io.Discard, out)
	}
	waitErr := cmd.Wait()
	if readErr != nil {
		return readErr
	}
	if waitErr != nil {
		return &CommandError{Args: args, Stderr: strings.TrimSpace(stderr.String()), Err: waitErr}
	}
	return nil
}

// CommandError is a failed git invocation with its stderr.
type CommandError struct {
	Args   []string
	Stderr string
	Err    error
}

func (e *CommandError) Error() string {
	name := "git"
	for i := 0; i < len(e.Args); i++ {
		if e.Args[i] == "-c" {
			i++ // skip the config value
			continue
		}
		if !strings.HasPrefix(e.Args[i], "-") {
			name = "git " + e.Args[i]
			break
		}
	}
	if e.Stderr != "" {
		return fmt.Sprintf("%s: %s", name, e.Stderr)
	}
	return fmt.Sprintf("%s: %v", name, e.Err)
}

func (e *CommandError) Unwrap() error { return e.Err }

func splitNUL(data []byte, atEOF bool) (int, []byte, error) {
	if i := bytes.IndexByte(data, 0); i >= 0 {
		return i + 1, data[:i], nil
	}
	if atEOF && len(data) > 0 {
		return len(data), data, nil
	}
	return 0, nil, nil
}
